name = "web-bot-auth"
main = "worker.js"
compatibility_date = "2026-07-01"
workers_dev = false
routes = [
  { pattern = "lancelotlabs.org/.well-known/http-message-signatures-directory*", zone_name = "lancelotlabs.org" },
]

[observability]
enabled = false
